### ISSUE TITLE
Rule for groovy: migration from `org.codehaus.groovy` to `org.apache.groovy`.

### ISSUE THREAD

**Issue by NielsDoucet** [gradlex-org/jvm-dependency-conflict-resolution#149]
With the [release of groovy 4](https://groovy-lang.org/releasenotes/groovy-4.0.html#Groovy4.0-naming-changes) the group id has changed from `org.codehaus.groovy` to `org.apache.groovy`.

Any chance this could become a rule in this plugin?

**Comment by jjohannes** [comment]
Could you clarify what you would expect the plugin to do in such a case?

The conflict detection is already provided by Groovy in the [published metadata](https://repo1.maven.org/maven2/org/apache/groovy/groovy/4.0.21/groovy-4.0.21.module):

```
     "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy",
          "version": "4.0.21"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy",
          "version": "4.0.21"
        }
      ]
```

What we could add to the plugin is some standard resolution strategy. For example, always select the highest version automatically if there is a conflict. But maybe this is not helpful, because libraries relying on Groovy 3 will most likely break if we "just" update the dependency to for.

**Comment by NielsDoucet** [comment]
We currently observe the following when a 3rd party library depends on an older version of groovy.
```log
   > Could not resolve org.codehaus.groovy:groovy:2.4.21.
     Required by:
         project :A > project :B > project :C > org.jfrog.artifactory.client:artifactory-java-client-services:2.17.0
      > Module 'org.codehaus.groovy:groovy' has been rejected:
           Cannot select module with conflict on capability 'org.codehaus.groovy:groovy:2.4.21' also provided by [org.apache.groovy:groovy:4.0.21(groovyRuntimeElements)]
```
In this particular case project `:C` has verified that it also functions when substituting the transitive dependency to groovy coming from the artifactory client library. 
But we'd like to avoid having to adapt the published metadata for that project though, as technically it should not force downstream projects to depend on groovy 4.
Project `:A` does depend on groovy 4 though, so it would be convenient to automatically resolve the conflict using the plugin in this case.

**Comment by jjohannes** [comment]
Thanks for elaborating. This is a specific situation in your setup, right? In the general case, silently updating to _Groovy 4_ most likely breaks 3rd party libraries because of the changed package.

The plugin has a DSL for defining your own strategy in a compact way. I would suggest you do this in your Gradle setup just after you applied the plugin:

```
jvmDependencyConflicts {
    conflictResolution.select("org.codehaus.groovy:groovy", "org.apache.groovy:groovy")
}
```

See [the docs](https://gradlex.org/jvm-dependency-conflict-resolution/#conflictResolution-dsl-block) for more details.
